# Generated by Django 3.1.1 on 2020-10-12 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fizzurl',
            old_name='shorten',
            new_name='shortcode',
        ),
    ]
