# Generated by Django 3.1.1 on 2020-10-12 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiz', '0002_auto_20201011_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fizzurl',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='fizzurl',
            name='shortcode',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='fizzurl',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
