# Generated by Django 3.1.1 on 2020-10-14 18:19

from django.db import migrations, models
import fiz.validators


class Migration(migrations.Migration):

    dependencies = [
        ('fiz', '0004_auto_20201012_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fizzurl',
            name='url',
            field=models.CharField(max_length=100, validators=[fiz.validators.url_validator, fiz.validators.dot_com_validator]),
        ),
    ]
